---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-client
  labels:
    app: perf-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perf-client
  template:
    metadata:
      labels:
        app: perf-client
    spec:
      containers:
      - name: perf-client
        image: quay.io/ralvares/qperf:latest
        env:
        - name: SERVICE_TYPE
          value: "iperf"
        - name: SERVER_ADDR
          value: "perf-server"
        - name: PERF_INTERVAL
          value: "10-60"
