---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qperf-client
  labels:
    app: qperf-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qperf-client
  template:
    metadata:
      labels:
        app: qperf-client
    spec:
      containers:
      - name: qperf-client
        image: quay.io/ralvares/qperf:latest
        env:
        - name: SERVICE_TYPE
          value: "client"
        - name: SERVER_ADDR
          value: "qperf-server"
        - name: SERVER_PORT
          value: "19765"
        - name: QPERF_INTERVAL
          value: "10-60"
