---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-server
  labels:
    app: perf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perf-server
  template:
    metadata:
      labels:
        app: perf-server
    spec:
      containers:
      - name: perf
        image: quay.io/ralvares/qperf:latest
        env:
        - name: SERVICE_TYPE
          value: "server"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: perf-server
  name: perf-server
spec:
  ports:
  - name: "19766"
    port: 19766
    protocol: TCP
    targetPort: 19766
  - name: "19765"
    port: 19765
    protocol: TCP
    targetPort: 19765
  - name: "5201"
    port: 5201
    protocol: TCP
    targetPort: 5201
  selector:
    app: perf-server
  type: ClusterIP
