---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qperf
  name: server
  labels:
    app: qperf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qperf-server
  template:
    metadata:
      labels:
        app: qperf-server
    spec:
      containers:
      - name: qperf
        image: quay.io/ralvares/qperf:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_TYPE
          value: "server"
        - name: SERVER_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  namespace: qperf
  name: server
  labels:
    app: qperf-server
spec:
  ports:
  - port: 8080
    name: server
  clusterIP: None
  selector:
    app: qperf-server
